### ISSUE TITLE
getting an error when running yarn start (yarn run)...

### ISSUE THREAD

**Issue by chagai95** [simison/couchspinner#3]
yarn run v1.22.5
$ react-scripts start
/bin/sh: 1: react-scripts: not found
error Command failed with exit code 127.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by simison** [comment]
Did you run just `yarn` first to install dependencies?

**Comment by chagai95** [comment]
Probably not can't remember..

**Comment by simison** [comment]
I tested locally and all works well. :-)
